# Estágio de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia e restaura as dependências apontando para a subpasta
COPY ["MedicaMais.API/MedicaMais.API.csproj", "MedicaMais.API/"]
RUN dotnet restore "MedicaMais.API/MedicaMais.API.csproj"

# Copia todo o código-fonte
COPY . .
WORKDIR "/src/MedicaMais.API"
RUN dotnet build "MedicaMais.API.csproj" -c Release -o /app/build

# Publicação dos arquivos compilados
FROM build AS publish
RUN dotnet publish "MedicaMais.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Estágio final de execução (Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MedicaMais.API.dll"]